sudo: required

language: go

go:
  - 1.8.x
  - 1.9.x
  - master

services:
  - docker

env:
  - POSTGRES_PASSWORD=mysecretpassword
  - POSTGRES_USER=test
  - POSTGRES_DB=test
  - POSTGRES_HOST=127.0.0.1
  - POSTGRES_PORT=4000

before_install:
  - docker pull postgres
  - docker run -d -p$POSTGRES_HOST:$POSTGRES_PORT:5432 postgres

install:
  - go get -t

script:
  - go vet
  - test -z "$(go fmt ./...)"